"""Add rating and helpful mark models

Revision ID: 68a262118f9e
Revises: 001
Create Date: 2025-05-27 19:54:53.139256

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68a262118f9e'
down_revision = '001'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prompts', sa.Column('average_rating', sa.Float(), nullable=True))
    op.add_column('prompts', sa.Column('rating_count', sa.Integer(), nullable=True))
    
    # 创建ratings表
    op.create_table('ratings',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('prompt_id', sa.UUID(), nullable=False),
        sa.Column('user_id', sa.UUID(), nullable=False),
        sa.Column('score', sa.Integer(), nullable=False),
        sa.Column('comment', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['prompt_id'], ['prompts.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    
    # 创建helpful_marks表
    op.create_table('helpful_marks',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('rating_id', sa.UUID(), nullable=False),
        sa.Column('user_id', sa.UUID(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['rating_id'], ['ratings.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # 删除helpful_marks表
    op.drop_table('helpful_marks')
    
    # 删除ratings表
    op.drop_table('ratings')
    
    # 删除prompts表中的列
    op.drop_column('prompts', 'rating_count')
    op.drop_column('prompts', 'average_rating')
    # ### end Alembic commands ###
