"""Add usage statistics models

Revision ID: 984d219c70b5
Revises: 68a262118f9e
Create Date: 2025-05-27 20:29:25.980803

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '984d219c70b5'
down_revision = '68a262118f9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # 创建usages表
    op.create_table('usages',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('prompt_id', sa.UUID(), nullable=False),
        sa.Column('user_id', sa.UUID(), nullable=True),
        sa.Column('usage_type', sa.String(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['prompt_id'], ['prompts.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    
    # 创建索引
    op.create_index('ix_usages_prompt_id', 'usages', ['prompt_id'], unique=False)
    op.create_index('ix_usages_user_id', 'usages', ['user_id'], unique=False)
    op.create_index('ix_usages_created_at', 'usages', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # 删除索引
    op.drop_index('ix_usages_created_at', table_name='usages')
    op.drop_index('ix_usages_user_id', table_name='usages')
    op.drop_index('ix_usages_prompt_id', table_name='usages')
    
    # 删除usages表
    op.drop_table('usages')
    # ### end Alembic commands ###
